#if !canImport(ObjectiveC)
import XCTest

extension TestSPMTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TestSPMTests = [
        ("testExample", testExample),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(TestSPMTests.__allTests__TestSPMTests),
    ]
}
#endif
